using System;
using System.Collections.Generic;

namespace AppCoreV1.AsteronModels;

public partial class Activity
{
    public long Id { get; set; }

    public long Activityclass { get; set; }

    public long? Activitypatternid { get; set; }

    public long? Assignedbyuserid { get; set; }

    public long? Assignedgroupid { get; set; }

    public long? Assignedqueueid { get; set; }

    public long? Assigneduserid { get; set; }

    public DateTime? Assignmentdate { get; set; }

    public long Assignmentstatus { get; set; }

    public string Autogenerated { get; set; } = null!;

    public long? Beanversion { get; set; }

    public long? Claimcontactid { get; set; }

    public long Claimid { get; set; }

    public DateTime? Closedate { get; set; }

    public long? Closeuserid { get; set; }

    public long? ComplaintExtid { get; set; }

    public DateTime? Createtime { get; set; }

    public long? Createuserid { get; set; }

    public string? Description { get; set; }

    public string Escalated { get; set; } = null!;

    public DateTime? Escalationdate { get; set; }

    public long? Exposureid { get; set; }

    public string Externallyowned { get; set; } = null!;

    public long? Externalownerccid { get; set; }

    public string? Generatedsource { get; set; }

    public long? Importance { get; set; }

    public DateTime? InitialescalationdateExt { get; set; }

    public DateTime? InitialtargetdateExt { get; set; }

    public DateTime? Lastvieweddate { get; set; }

    public string Mandatory { get; set; } = null!;

    public long? Previousgroupid { get; set; }

    public long? Previousqueueid { get; set; }

    public long? Previoususerid { get; set; }

    public long Priority { get; set; }

    public string Publicid { get; set; } = null!;

    public string Recurring { get; set; } = null!;

    public long Retired { get; set; }

    public long? ScRejectreason { get; set; }

    public long Status { get; set; }

    public string? Subject { get; set; }

    public long Subtype { get; set; }

    public DateTime? Targetdate { get; set; }

    public long Type { get; set; }

    public DateTime? Updatetime { get; set; }

    public long? Updateuserid { get; set; }

    public long? Validationlevel { get; set; }
}
